
muddawitze = [
    "Deine Mudda heißt Dieter und ist der Haarigste im Zoo.Deine Mudda legt sich zum Schlafen auf´s Bett. Das Bett sagt mit letzter Kraft zum Sessel: 'Rächt mich.'",
    "Deine Mudda ist so fett, als sie das letzte mal im Meer baden war, kam ein japanisches Fischerboot, um sie zu harpunieren.",
    "Deine Mudda stinkt sogar auf Fotos! Deine Mudda schreit von der Toilette: „Schaut mal Kinder, ich bin ein 3D Drucker.”",
    "Wenn deine Mudda tanzen geht, bekommt der Begriff „Walzer“ eine ganz neue Bedeutung.",
    "Was passiert, wenn deine Mudda einen Polizisten ansieht? - Sie bekommt eine Strafanzeige wegen Beamtenbeleidigung",
    "Deine Mudda ist so arm, sie rennt, mit einer Einkaufliste, dem Müllwagen hinterher.",
    "Deine Mudda wurde Letztens bei Kik als Umkleidekabine verwechselt.",
    "Wenn deine Mudda im Aldi furzt, ist am nächsten Tag dort alles zu 80% reduziert.",
    "Deine Mudda ist so hässlich, dein Vater nimmt sie mit auf die Arbeit, damit er ihr kein Abschiedskuss geben muss.",
    "Es gibt kein Australien. Das ist deine Mudda.",
    "Wenn euer Hund im Auto furzt, macht deine Mudda die Scheiben hoch.",
    "Deine Mudda ist so alt, sie furzt Staub.",
    "Deine Mudda ist so hässlich bei ihr wird eingebrochen, um die Vorhänge zu schließen.",
    "Kennst du den Unterschied zwischen Milch und deiner Mudda? - Die Milch gibt es auch in fettarm.",
    "Die Amerikaner brauchen keine Mauer. Ein paar Poster von deiner Mudda reichen.",
    "Deine Mudda ist so fett und hässlich, sie kann einen ganzen Mob aufhalten.",
    "Deine Vater kämmt die Rückenhaare deiner Mudda mit einer Harke.",
    "Wenn euer Familienhund deine Mudda beim essen zuschaut, bekommt er einen Würgreiz.",
    "Es waren keine Terroristen, die die Word Trade Center einstürzen ließen. Es war deine Mudda. Sie hat gefurzt. Das hat die Flugzeuge da reingeweht.",
    "Deine Mudda ist so hässlich, wenn sie einen Bumerang wirft, weigert sich dieser zurück zu kommen.",
    "Wenn deine Mudda pupst, klatschen die Stinktiere respektvoll Beifall.",
    "Deine Mudda hat so viel Körperbehaarung, 'Planet der Affen' ist für sie ein Heimatfilm.",
    "Deine Mudda ist so hässlich, Gott musste sofort das Licht ausmachen, nachdem er 'Es werde Licht' gesagt hat.",
    "Wenn deinen Mudda nicht in das Schwimmbecken gesprungen wäre, dann hätte Nasa auf dem Mars kein Wasser gefunden.",
    "Wenn deine Mamma spät abends vor die Tür geht, gehen die Straßenlaternen wieder aus.",
    "Deine Mudda ist so fett, auf ihr werden Flächen vermietet.",
    "Deine Mudda ist so hässlich, wenn sie sich im Spiegel ansieht, sagt der Spiegel: 'Boah, ich kündige!'",
    "Man benutzt deine Mudda als Sterbehilfe.",
    "Deine Mudda hat so lange Arschhaare, dass sie beim Spülen mit runtergezogen wird.",
    "Deine Mudda hat Hausverbot im Zoo, weil es die Tiere verstört, wenn sie kommt.",
    "Deine Mudda arbeitet im Gefängnis als Bestrafung.",
    "Wenn deine Mudda durchs Fenster schaut, fängt Satan an zu kotzen.",
    "Deine Mudda steigt von beiden Seiten aus dem Bett.",
    "Deine Mudda ist so hässlich, sie wurde vor kurzem vom Psychiatrie-Knast eingestellt, um Sexualstraftäter zu kurieren.",
    "Man hat deine Mudda mit einer Brotkruste aus dem Wald gelockt.",
    "Wenn deine Mudda in den Zoo geht, versuchen die Besucher sie zu füttern.",
    "Wenn deine Mudda sagt: 'Hey, ich bin auch nur ein Mensch', dann ruft die Wage aus dem Badezimmer: „Anderthalb Menschen!“",
    "Wenn ich mit deiner Mudda spazieren gehe, nehme ich vorsichtshalber Kot-Beutel mit.",
    "Deine Mudda tanzt Limbo durch das Brandenburger Tor.",
    "Deine Mudda sammelt Pilze, aber nicht im Wald.",
    "Deine Mudda ist so fett, sie ist auf beiden Seiten des Familienfotos.",
    "Deine Mudda war als Neugeborenes so fett, ihr Geburtstag ist vom 17. bis zum 23. März.",
    "Deine Mudda ist so fett, sie hat einmal einen Zug bestiegen und danach konnte der Zug aufgrund eines unbekannten technischen Fehlers nicht losfahren.",
    "Jetzt weiß ich wie die Dinosaurier ausgestorben sind. Jemand hat den Pups deiner Mudda angezündet.",
    "Deine Mudda ist selbst in Minecraft rund.",
    "Wenn der Geier ausstirbt, ist deine Mudda wieder der hässlichste Vogel.",
    "Deine Mudda kriegt beim Elternabend einen Klassenbucheintrag.",
    "Warum kann deine Mudda nicht zu Gott in den Himmel? - Sie passt nicht durch das Ozonloch.",
    "Deine Mudda wird von Elfenbeinjägern verfolgt!",
    "Deine Mudda ist die garstigste im Knast.",
    "Deine Mudda ist so geizig, wenn sie kotzt beißt sie die Zähne zusammen, um die Bröckchen zu behalten.",
    "Wenn deine Mudda in den Fahrstuhl steigt, geht der nur nach Unten.",
    "In Deutschland gibt es laut der Zeitung wieder Wölfe. Grund für diese Meldung: Deine Mudda hat zu laut gestöhnt.",
    "Wenn deine Mudda einen Pups loslässt, ist es sogar für die Stinktiere ganz schlimm.",
    "Wenn sich deine Mudda vor einen Spiegel stellt, schreit das Glas kurz auf und zerbricht.",
    "Wenn ich deine Mudda ansehe, finde ich mich wieder schön.",
    "Die Nasa hat angerufen, dein Mudda zieht uns aus der Umlaufbahn.",
    "Deine Mudda ist so fett, wenn sie spazieren geht, behängt sie sich mit einem 'Umleitung'-Schild.",
    "Als deine Mudda nach Tschernobyl gezogen ist, sind dann auch die letzten Menschen weggezogen.",
    "Deine Mudda ist so fett, wenn sie in der Nordsee baden geht, hebt sich der Wasserspiegel aller deutschen Flüsse.",
    "Deine Mudda ist so fett, sie muss zum Wiegen ins Kieswerk.",
    "Deine Mudda arbeitet bei Dixiklo also Gestank.",
    "Deine Mudda ist so fett, wenn sie mit High-Heels ausgeht, kommt sie mit Flip-Flops zurück.",
    "Deine Mudda bellt, wenn's an der Tür klingelt.",
    "Deine Mudda zündet sich'n Furz an und schreit: 'Flammenwerfer'",
    "Deine Mudda ist so fett, dass sie beim Bunggee-Jumping die ganze Brücke mitreist.",
    "Deine Mudda ist so hässlich, sie geht in ein echtes Spukhaus und kommt mit einem Bewerbungsformular raus.",
    "Deine Mudda ist die beste im Jägerverein. Sie braucht nur in den Wald gehen und schon ergeben sich die Tiere und kommen von alleine raus.",
    "Dein Mudda haut sich jeden Morgen zwei Pfannen in die Eier.",
    "Deine Mudda ruft beim Kummerkasten an, weil ihr die Toilette zu klein geworden ist.",
    "Deine Mudda ist so dumm, sie erzählt Weisenkindern 'Deine Mudda'-Witze.",
    "Deine Mudda kann einfach nur stinken!",
    "Deine Mudda kriegt bei Fressnapf an der Kasse ein Leckerli.",
    "Deine Mudda ist so hässlich, sie arbeitet beim FBI als Blendgranate.",
    "Deine Mudda ist so fett, neben ihr sieht Moby Dick aus wie ein Tic-Tac.",
    "Das Lieblingsgetränk deiner Mudda ist altes Wurstwasser.",
    "Deine Mudda ist so dumm, sie macht auf der Toilette immer das Fenster auf und schreit hinaus: ICH WAR GERADE EBEN SCHEISSEN UND FÜHLE MICH 10 TONNEN LEICHTER.",
    "Deine Mudda ist so fett, der Toilettensitz hat keinen Bock mehr.",
    "Deine Mudda stöhnt beim Pupsen.",
    "Deine Mudda ist so fett, dass sie vom Stammbaum abgebrochen ist...",
    "Deine Mudda hat in den Vorhof geschissen. Bitte wegmachen.",
    "Deine Mudda klaut Probiersöckchen bei Deichmann! Und zwar immer alle.",
    "Deine Mudda ist so heftig dick; wenn sie auf das Sprungbrett im Freibad geht, sagt der Bademeister: 'Ist das jetzt ein Scherz, wer hat das Auto da oben geparkt?'",
    "Deine Mudda furzt ins Badewannenwasser und singt 'O2 can do'.",
    "Deine Mudda is so fett, sie guckt die Speisekarte an und sagt zum Kellner: 'ok'.",
    "Deine Mudda ist so fett, wenn sie vor deinem Haus steht, habt ihr 3 Tage kein W-Lan.",
    "Als Bob der Baumeister deine Mudda sah, hat er gesagt: Das können wir nicht schaffen.",
    "Deine Mudda ist so hässlich, bei einer Zombie-Apocalypse laufen die Zombies automatisch in die andere Richtung.",
    "Deine Mudda ist so fett, wenn man auf ein Hochhaus steigt, um sie von oben endlich mal in klein zu sehen, ist sie immer noch genauso fett.",
    "Deine Mudda ist so fett, die ist letztens von einem LKW überfahren worden, jedoch ist der LKW im Bauchnabel stecken geblieben.",
    "Deine Mudda uriniert ins Kinderbecken.",
    "Deine Mudda verpetzt deinen Vater, wenn er versucht, hinten im Bus umsonst einzusteigen.",
    "Deine Mudda ist so arm, als ich bei euch gefurzt habe, fragt sie, wer die Heizung angemacht hat.",
    "Deine Mudda darf sich nicht in der Nähe von Wärmequellen Aufhalten. Begründung: Entzündliche Gase",
    "Wenn deine Mudda im Schulhof auf dich wartet, verdunkelt sich das Klassenzimmer.",
    "Deine Mudda findet am Schrottplatz einen Spiegel und sagt: 'So ein Bild hätte ich auch weggeworfen!'",
    "Deine Mudda ist so fett, Terroristen benutzen Sie als tickende Fressbombe.",
    "Wenn deine Mudda baden geht, rufen die Kinder 'Wer zuerst auf der Insel ist'"
    ]
