
canteens = {
    "Mensa UniCampus Magdeburg": "1",
    "Magdeburg Herrenkurg": "2",
    "Mensa Stendal": "3",
    "Mensa Wernigerode": "4",
    "DomCafete Halberstadt": "5",
    "Hannover Hauptmensa": "6",
    "Hannover, Contine": "7",
    "Mensa PZH": "8",
    "Mensa Caballus": "9",
    "Mensa TiHo-Tower": "10",
    "Mensa HMTMH": "11",
    "Mensa Ricklinger Stadtweg": "12",
    "Hannover, Mensa/Cafeteria Blumhardtstraße": "13",
    "Hannover, Mensa Große Pause": "14",
    "Hannover, Cafeteria Herrenhausen": "15",
    "Hannover Hauptmensa Marktstand": "16",
    "Hannover, Restaurant c. t.": "17",
    "Cafeteria FU Wirtschaftswissenschaften": "18",
    "Mensa Beuth Hochschule für Technik Kurfürstenstraße": "19",
    "Cafeteria FU Rechtswissenschaft": "20",
    "Cafeteria FU Pharmazie": "21",
    "Mensa Charité Zahnklinik": "22",
    "Cafeteria TU Ernst-Reuter-Platz": "23",
    "Mensa HTW Wilhelminenhof": "24",
    "Mensa ASH Berlin Hellersdorf": "25",
    "Cafeteria FU Otto-Suhr-Institut": "26",
    "Mensa FU II Otto-von-Simson-Straße": "27",
    "Mensa FU Veggie Nº 1": "28",
    "Mensa HWR Badensche Straße": "29",
    "Mensa HTW Treskowallee": "30",
    "Karlsruhe, Mensa Am Adenauerring": "31",
    "Karlsruhe, Mensa Moltke": "32",
    "Karlsruhe, Mensa Erzbergerstraße": "33",
    "Karlsruhe, Mensa Schloss Gottesaue": "34",
    "Pforzheim, Mensa Tiefenbronner Straße": "35",
    "Mensa TU Hardenbergstraße": "36",
    "Mensa HU Spandauer Straße": "37",
    "Mensa EHB Teltower Damm": "38",
    "Pforzheim, Mensa Holzgartenstraße": "39",
    "Mensa KHS Weißensee": "40",
    "Cafeteria FU Koserstraße": "41",
    "Mensa FU Herrenhaus Düppel": "42",
    "Mensa HU Süd": "43",
    "Cafeteria HfM 'Neuer Marstall'": "44",
    "Cafeteria TU 'Skyline'": "45",
    "Cafeteria UdK 'Jazz-Cafe'": "46",
    "Mensa HfS Schnellerstraße": "47",
    "Mensa HU Nord": "48",
    "Mensa Beuth Hochschule für Technik Luxemburger Straße": "49",
    "Mensa HU Oase Adlershof": "50",
    "Mensa HfM Charlottenstraße": "51",
    "Mensa FU Lankwitz Malteserstraße": "52",
    "Cafeteria TU Ackerstraße": "53",
    "Mensa Katholische HS für Sozialwesen": "54",
    "Mensa Am Neuen Palais": "55",
    "Cafeteria TU Hardenbergstraße": "56",
    "Mensa Kiepenheuerallee": "57",
    "Mensa Wildau": "58",
    "Mensa Brandenburg": "59",
    "Mensa Friedrich-Ebert-Str.": "60",
    "Mensa Golm": "61",
    "Mensa Griebnitzsee": "62",
    "Leipzig, Mensa am Park": "63",
    "Leipzig, Mensa Academica": "64",
    "Leipzig, Mensa Am Elsterbecken": "65",
    "Leipzig, Mensa An den Tierkliniken": "66",
    "Leipzig, Mensa Liebigstraße": "67",
    "Leipzig, Mensa Peterssteinweg": "68",
    "Leipzig, Mensa/Cafetaria Schönauer Straße": "69",
    "Leipzig, Cafeteria Dittrichring": "70",
    "Leipzig, Cafeteria Koburger Straße": "71",
    "Leipzig, Cafeteria Philipp-Rosenthal-Straße": "72",
    "Leipzig, Cafeteria Wächterstraße": "73",
    "Mensa Philosophenweg": "74",
    "Mensa Ernst-Abbe-Platz": "75",
    "Mensa Carl-Zeiss-Promenade": "76",
    "Dresden, Zeltschloesschen": "78",
    "Dresden, Alte Mensa": "79",
    "Dresden, Mensa Reichenbachstraße": "80",
    "Dresden, Mensologie": "81",
    "Dresden, Mensa Siedepunkt": "82",
    "Tharandt, Mensa TellerRandt": "83",
    "Dresden, Mensa Palucca Schule": "84",
    "Dresden, Mensa WUeins": "85",
    "Dresden, Mensa Stimm-Gabel": "86",
    "Dresden, Mensa Johannesstadt": "87",
    "Dresden, BioMensa U-Boot": "88",
    "Mensa Zittau": "89",
    "Mensa Zittau Haus VII": "90",
    "Dresden, Mensa Sport": "91",
    "Dresden, Mensa Kreuzgymnasium": "92",
    "Aachen, Forum Cafete": "93",
    "Aachen, Bistro Templergraben": "94",
    "Aachen, Mensa Ahorn": "95",
    "Aachen, Mensa Vita": "96",
    "Aachen, Mensa Bayernallee": "97",
    "Aachen, Mensa EUPS": "98",
    "Aachen, Gastro Goethe": "99",
    "Mensa Jülich": "100",
    "Bamberg, Mensa Austraße": "101",
    "Bamberg, Mensa Feldkirchenstraße": "102",
    "Mensa Aschaffenburg": "103",
    "Bistro Tasty Studio Babelsberg": "104",
    "Mensa Schweinfurt": "105",
    "Würzburg, Mensa Burse": "106",
    "Würzburg, Mensa Frankenstube": "107",
    "Würzburg, Mensa am Hubland": "108",
    "Würzburg, Mensa am Studentenhaus": "109",
    "Würzburg, Mensa Augenklinik": "110",
    "Würzburg, Mensa Josef-Schneider-Straße ": "111",
    "Ulf's Café (HPI Cafeteria)": "112",
    "Marburg, Mensa Erlenring": "113",
    "Marburg, Mensa Lahnberge": "114",
    "Marburg, Philipps Bistro": "115",
    "Marburg, Mo's Diner": "116",
    "Hamburg, Mensa Armgartstraße": "117",
    "Hamburg, Mensa Bergedorf": "118",
    "Hamburg, Mensa Berliner Tor": "119",
    "Hamburg, Café Averhoffstraße": "120",
    "Hamburg, Mensa Botanischer Garten": "121",
    "Hamburg, Mensa Bucerius Law School": "122",
    "Hamburg, Café Jungiusstraße": "123",
    "Hamburg, Café Alexanderstraße": "124",
    "Hamburg, Mensa Campus": "125",
    "Hamburg, Mensa City Nord": "126",
    "Hamburg, Mensa Finkenau": "127",
    "Hamburg, Mensa Geomatikum": "128",
    "Hamburg, Mensa Harburg   ": "129",
    "Hamburg, Mensa Philosophenturm": "130",
    "Hamburg, Mensa Stellingen": "131",
    "Hamburg, Mensa Studierendenhaus": "132",
    "Mensa Leopoldstraße": "133",
    "Mensa Martinsried": "134",
    "Mensaria Großhadern": "135",
    "StuBistro Schellingstraße": "136",
    "StuBistro Goethestraße": "137",
    "Mensa Arcisstraße": "138",
    "Mensa Garching": "139",
    "Mensa Weihenstephan": "140",
    "Mensa Lothstraße": "141",
    "Mensa Pasing": "142",
    "Cafeteria Olympiapark": "143",
    "StuCafé in der Mensa Garching": "144",
    "StuCafé Akademie Weihenstephan": "145",
    "StuCafé Boltzmannstraße": "146",
    "Mensa Nordhäuser Straße": "147",
    "Mensa Altonaer Straße": "148",
    "NANOteria": "149",
    "Mensa Ehrenberg": "150",
    "Mensa am Park": "151",
    "Mensa Berufsakademie Gera ": "152",
    "Mensa 1 (Mittag)": "153",
    "Mensa 1 (Abend)": "154",
    "Mensa 2": "155",
    "Kantina Kreativa": "156",
    "Magdeburg, Mensa UniCampus Oben": "157",
    "Mensa Clausthal": "158",
    "Mensa Universität": "159",
    "Mensa Hohnsen (HAWK)": "160",
    "Bistro-Shop Lübecker Straße": "161",
    "Mensa HAWK": "162",
    "Mensa Campus": "163",
    "Lüneburg, Mensa Rotes Feld": "164",
    "Mensa Suderburg": "165",
    "Mensa Ostfalia": "166",
    "Uni Mensa": "167",
    "Mensa Neustadtswall": "168",
    "Mensa Werderstrasse": "169",
    "Mensa am Airport": "170",
    "Mensa Bremerhaven": "171",
    "Cafeteria GW2": "172",
    "Darmstadt, Mensa Stadtmitte": "173",
    "Darmstadt, Mensa Lichtwiese": "174",
    "Darmstadt, Mensa Schöfferstraße": "175",
    "Darmstadt, Mensa Dieburg": "176",
    "Darmstadt, Bistro Haardtring": "177",
    "360 Grad": "178",
    "Göttingen, Zentralmensa": "179",
    "Göttingen, Nordmensa": "180",
    "Göttingen, Mensa am Turm": "181",
    "Göttingen, Mensa Italia": "182",
    "Göttingen, Bistro HAWK": "183",
    "Hamburg, Cafe am Mittelweg": "184",
    "Hamburg, Cafe CFEl": "185",
    "Hamburg, Mensa HCU": "186",
    "Aachen, Mensa Academica": "187",
    "Kochwerk Elbe": "188",
    "BioMensa U-Boot": "190",
    "Mensa Brühl": "191",
    "Gebze Yüksek Teknoloji Enstitüsü": "192",
    "Konstanz, HTWG": "193",
    "Mensa UNI Regensburg": "194",
    "Mensa OTH Regensburg": "195",
    "Mensa UNI Passau": "196",
    "Mensa HS Landshut": "197",
    "Mensa TH Deggendorf": "198",
    "Kochwerk Alster": "199",
    "Dresden, Mensa Brühl": "200",
    "Mensa NW 1": "201",
    "Mensa Rüsselsheim": "202",
    "Uni-Bielefeld Mensa": "203",
    "mensa accent": "204",
    "Mensa Pi x Gaumen": "205",
    "Mensa Casino": "206",
    "Cafeteria LEVEL": "207",
    "Cafeteria Darwins": "208",
    "Mensa Anbau Casino": "209",
    "Cafeteria DASEIN": "210",
    "Cafeteria Bockenheim": "211",
    "Café HOCHFORM": "212",
    "Mensa essWERK": "213",
    "Mensa HfMDK": "214",
    "Cafeteria HfG": "215",
    "Mensa POINT": "216",
    "Mensa am Ring": "225",
    "Mensa am Aasee": "226",
    "Bistro Denkpause": "227",
    "Mensa da Vinci": "228",
    "StuBistro Rosenheim": "229",
    "StuCafé Adalbertstraße": "230",
    "StuCafé Mensa-WST": "231",
    "StuCafé Karlstraße": "232",
    "Mensa Bispinghof": "233",
    "Erfrischungshalle": "234",
    "Mensa Burg": "235",
    "Mensa Franckesche Stiftungen": "236",
    "Mensa Merseburg": "237",
    "Heidemensa": "238",
    "Mensa Neuwerk": "239",
    "Weinbergmensa": "240",
    "Mensa Bernburg": "241",
    "Mensa Dessau": "242",
    "Harzmensa": "243",
    "Mensa Fasanerieallee": "244",
    "Mensa Tulpe": "245",
    "Kantine KIT Campus Nord": "246",
    "Bistro4u NFF": "247",
    "Mensa Westfälische Hochschule Standort Bocholt": "248",
    "Mensa Uni Bayreuth - Campus": "249",
    "AR": "251",
    "ENC": "252",
    "Mark": "253",
    "Mensa Kassel": "254",
    "Erlangen Südmensa": "256",
    "Mensa Uni Paderborn": "257",
    "Mensa Fulda": "258",
    "Würz­burg, Mensateria Campus Nord": "259",
    "Mensa und Cafeteria Lübeck": "260",
    "Mensa / Mensacafe Saarbrücken": "261",
    "Kanti Reussbühl": "262",
    "SV (Schweiz) AG ,Kantonsschule Reussbühl ": "263",
    "Mensa Langemarckplatz": "264",
    "Mensa Insel Schütt": "265",
    "Mensa Regensburger Straße": "266",
    "Ausgabemensa St. Paul": "267",
    "Mensateria Ohm": "268",
    "Cafeteria 'Come IN' Hohfederstraße": "269",
    "Cafeteria Bärenschanzstraße": "270",
    "Cafeteria Eichstätt": "271",
    "Cafeteria Ingolstadt": "272",
    "Mensateria Gastwirtschaft zum Adler Triesdorf": "273",
    "Mensa Ansbach": "274",
    "Mensa OBS": "275",
    "Cafeteria Café Phil": "276",
    "Heilbronn, Mensa Bildungscampus/Europaplatz": "277",
    "Heilbronn, Mensa Sontheim": "278",
    "Heidelberg, Mensa Im Neuenheimer Feld 304": "279",
    "Künzelsau, Mensa Reinhold-Würth-Hochschule": "280",
    "Heidelberg, Triplex-Mensa am Uniplatz": "281",
    "Heidelberg, zeughaus-Mensa im Marstall": "282",
    "Mannheim, Mensaria Metropol": "283",
    "Mannheim, Cafeteria KUBUS": "284",
    "Mannheim, Mensa am Schloss": "285",
    "Mannheim, Cafeteria Musikhochschule": "286",
    "Mannheim, Mensaria Wohlgelegen": "287",
    "Mannheim, EO (Schloss Ehrenhof)": "288",
    "Mannheim, Mensa Hochschule Mannheim": "289",
    "Theologische Hochschule Friedensau": "290",
    "Kiel, Mensa I am Westring": "291",
    "Kiel, Mensa II": "292",
    "mensa uni augsburg": "293",
    "Mensa Süd": "294",
    "Campus Cafeteria Einstein": "295",
    "Chemnitz, Reichenhainer Straße, Mensa": "296",
    "Chemnitz, Straße der Nationen, Mensa": "297",
    "Zwickau, Ring, Cafeteria": "298",
    "Zwickau, Scheffelberg, Cafeteria": "299",
    "Abendmensa OTH Regensburg": "300",
    "Mensa Oldenburg": "301",
    "Mensa Witzenhausen": "302",
    "Chemnitz, Reichenhainer Straße, Cafeteria": "303",
    "Chemnitz, Straße der Nationen, Cafeteria": "304",
    "Zwickau, Ring, Mensa": "305",
    "Zwickau, Scheffelberg, Mensa": "306",
    "Europa Universität Viadrina ": "307",
    "Cafeteria Uni-Hauptgebäude": "308",
    "Cafeteria ThULB": "309",
    "Mensa WZ Straubing": "310",
    "Mensa im Campus Berlin-Buch": "311",
    "Hochschule Ruhr West": "312",
    "Cafeteria Nikolakloster Passau": "313",
    "Cafeteria Prüfening Regensburg": "314",
    "Cafeteria Philosophie-Theologie (PT) Regensburg": "315",
    "Cafeteria Chemie Regensburg": "316",
    "Cafeteria Milchbar Regensburg": "317",
    "Cafeteria Sammelgebäude Regensburg": "318",
    "Cafeteria Sport Regensburg": "319",
    "Mensa Flensburg": "320",
    "Mensa Institutsviertel": "321",
    "Mensa Rempartstrasse": "322",
    "Hauptmensa Duisburg": "323",
    "Hauptmensa Essen": "324",
    "Bistro Coerdehof": "325",
    "Bistro Durchblick": "326",
    "Bistro Frieden": "327",
    "Bistro Hüfferstift": "328",
    "Bistro KaBu": "329",
    "Bistro Katholische Hochschule": "330",
    "Bistro Oeconomicum": "331",
    "Mensa Steinfurt": "332",
    "Hauptmensa am HoPla": "333",
    "Mensa Ruhr-Universität Bochum": "334",
    "Mensa & Cafeteria Wilhelmstraße, Tübingen": "335",
    "Düsseldorf, Mensa Universitätsstraße": "336",
    "Düsseldorf, restaurant & bar campus vita": "337",
    "Düsseldorf, Essensausgabe Uni Süd": "338",
    "Mensa Universitätsstraße, Düsseldorf": "339",
    "Mensa Kamp-Lintfort": "340",
    "Mensa Campus Derendorf": "341",
    "Mensa Georg-Glock-Straße, Düsseldorf": "342",
    "Mensa Obergath, Krefeld": "343",
    "Mensa Frankenring, Krefeld": "344",
    "Mensa Sommerdeich, Kleve": "345",
    "Mensa Rheydter Straße, Mönchengladbach": "346",
    "restaurant & bar campus vita, Düsseldorf": "347",
    "Essenausgabe Süd, Düsseldorf": "348",
    "Kunstakademie, Düsseldorf": "349",
    "Musikhochschule, Düsseldorf": "350",
    "JimmiXzSw": "351",
    "Mensa Westerberg": "352",
    "Mensa Uni Stuttgart": "353",
    "Zentralmensa JGU Mainz": "354",
    "Hochschule Augsburg": "355",
    "Schwentine Mensa": "356",
    "mensa greifswald": "357",
    "Mensa Kellercafé": "358",
    "Studierendenwerk Ulm an der Uni Ulm": "359",
    "IWZ Deutz": "360",
    "Mensa TU Kaiserslautern": "361",
    " CAMPO Campusmensa Poppelsdorf": "362",
    "Mensa FH Kaiserslautern ": "363",
    "Mensa Campus Lichtenberg": "364",
    "Mittweida ": "365",
    "Mensa Hohenheim": "366",
    "Rostock, Mensa Süd": "367",
    "Rostock, Mensa E1nstein": "369",
    "Rostock, Mensa St.-Georg-Straße": "370",
    "Rostock, Mensa Multiple Choice": "371",
    "Rostock, Mensa Ulme": "372",
    "Rostock, Mensa Ulme 69": "373",
    "Wismar, Campus Mensa": "374",
    "Universität": "375",
    "Cafeteria FH Lampingstraße": "376",
    "Mensa Hochschule OWL Lemgo": "377",
    "Mensa Hochschule OWL Höxter": "378",
    "Uni-Bielefeld Westend": "379",
    "Casino Cafeteria": "381",
    "MensaXss": "382",
    "Köln, Mensa Südstadt": "383",
    "Köln, Mensa Zülpicher Straße": "384",
    "Köln, Mensa Kunsthochschule Medien": "385",
    "Köln, Mensa Robert-Koch-Straße": "386",
    "Köln, Mensa Deutz": "387",
    "Köln, Mensa Musikhochschule": "388",
    "Köln, Mensa am Sportpark Müngersdorf": "389",
    "Gummersbach, Mensa Gummersbach": "390",
    "Köln, Café Himmelsblick, Claudiusstraße": "391",
    "Stuttgart Mitte, Mensa 1 (Holzgartenstraße)": "392",
    "Ludwigsburg, Mensa Ludwigsburg": "393",
    "Stuttgart Nord, Mensa Kunstakademie": "394",
    "Stuttgart Mitte, Mensa Musikhochschule": "395",
    "Esslingen, Mensa Stadtmitte - Kanalstraße": "396",
    "Esslingen, Mensa Flandernstraße": "397",
    "Göppingen, Cafeteria Bau 4 EG": "398",
    "Stuttgart Vaihingen, Mensa 2": "399",
    "JimmiNu": "400",
    "Mensa HfM Detmold": "401",
    "Mensa Überseering": "402"
}
