"Davos: Robert Habeck nennt Donald Trumps Rede ein \"Desaster\" - ZEIT ONLINE",
  "Impeachment: Donald Trumps Sensenmann im Senat \u2013 McConnell legt Plan vor - t-online.de",
  "Gleicher Preis f\u00fcr weniger Ware: Mir\u00e1coli ist \"Mogelpackung des Jahres\" - tagesschau.de",
  "Schw\u00e4bisch Gm\u00fcnd - Dreij\u00e4hriger stirbt bei Kindergartenausflug - S\u00fcddeutsche Zeitung",
  "K\u00f6ln-M\u00fclheim: Polizei findet zwei Tote in einer Wohnung - EXPRESS",
  "Befreiung von Auschwitz: Ausstellung zeigt \u00dcberlebende des Holocaust in Essen - t-online.de",
  "Dorfkinder: Kl\u00f6ckner-Ministerium wirbt f\u00fcrs Landleben - Debatte eskaliert schnell und extrem heftig | Politik - Merkur.de",
  "Bombe in K\u00f6ln-Deutz entsch\u00e4rft - Zugverkehr war betroffen - RP ONLINE",
  "Nachrichten aus Deutschland: S\u00e4ugling ausgesetzt - Polizei ver\u00f6ffentlicht Fotos - STERN.de",
  "Beleidigungen: Teilerfolg f\u00fcr Renate K\u00fcnast wegen Hasspostings bei Facebook - ZEIT ONLINE",
  "Libyen-Konferenz: Putin kommt nicht - da zeigt ihm Merkel, wo es langgeht | Politik - Merkur.de",
  "Neues Coronavirus - Zahl der Infektionen in China steigt auf mehr als 290 - S\u00fcddeutsche Zeitung",
  "Russische Verfassungsreform: Wladimir Putin will Amtszeiten des Pr\u00e4sidenten beschr\u00e4nken - ZEIT ONLINE",
  "Fl\u00fcchtlinge \u00fcberqueren Grenzfluss zu Mexiko - tagesschau.de",
  "Dieselskandal: Razzia beim Autobauer Mitsubishi - t-online.de",
  "E-Auto mit Solarmodulen: Sono Motors erreicht Crowdfunding-Ziel - heise online",
  "K\u00fcnstliche Intelligenz: EU-Kommission will rechtlichen Rahmen schaffen - WELT",
  "O2 streicht Weitersurf-Garantie in den neuen Tarifen - Caschys Blog",
  "Keine Software-Updates f\u00fcr alte Hardware: Sonos klemmt seine treuesten Kunden ab - DER SPIEGEL",
  "Radeon RX 5600 XT im Test: Doch noch ein Konkurrent f\u00fcr die GeForce RTX 2060 - ComputerBase",
  "Auf Druck des FBI: Apple iCloud-Backups ohne Vollverschl\u00fcsselung - iphone-ticker.de \u203a iPhone-News seit 2007",
  "Windows 7: Verl\u00e4ngerter Support kostet Bundesregierung Hunderttausende Euro - heise online",
  "Schweben Harry und Meghan in Lebensgefahr? Personensch\u00fctzer mit eindringlicher Warnung | Boulevard - Merkur.de",
  "Krasse Dschungelcamp-Vorw\u00fcrfe: \"Hetze vom Team\" - OK! Magazin",
  "Daniela Katzenberger: Sie musste ihr Hotel verlassen: \"Ich dachte zuerst, das sei ein Scherz\" - BUNTE.de",
  "Joseph Hannesschl\u00e4ger: Kollegen nehmen in Traueranzeige Abschied - RND",
  "DHB gibt bekannt: Christian Prokop bleibt Bundestrainer - t-online.de",
  "FC Bayern: Alvaro Odriozola von Real Madrid im Anflug - keine Freigabe f\u00fcr Cancelo - SPOX",
  "1. FC K\u00f6ln: Lukas Podolski vor R\u00fcckkehr in \"kurzfristiger Zusammenarbeit\" - SPORT1",
  "Alexander Zverev will bei Australian Open Preisgeld komplett spenden - BILD",
  "Alzheimer breitet sich wie eine Infektion im Gehirn aus | Netzwelt - hna.de",
  "Waln\u00fcsse gut f\u00fcr Darm- und Herzgesundheit - Nau.ch",
  "Geb\u00e4rmutterhalskrebs: Effiziente Fr\u00fcherkennung und Vorsorge - Stol.it",
  "Lootboxen f\u00f6rdern Spielsucht bei Kindern und Jugendlichen \u2013 sagt britischer Gesundheitsdienst - Giga"
